apiVersion: v1
kind: Service
metadata:
  name: rms-service
spec:
  selector:
    app: rms-docker-img  # Must match the "app" label in Deployment!
  type: LoadBalancer
  ports:
    - port: 80          # External port
      targetPort: 5050  # Must match app listening port
      protocol: TCP
